# Generated by Django 3.0.1 on 2020-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcrecord',
            name='course',
            field=models.ManyToManyField(related_name='tcrecord', to='course.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='tc_crse_reg', to='course.Course'),
        ),
    ]
