# Generated by Django 3.0.1 on 2020-05-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dptclass', '0001_initial'),
        ('school', '0001_initial'),
        ('department', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_dpt', to='department.Department'),
        ),
        migrations.AddField(
            model_name='student',
            name='dptclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_dptcls', to='dptclass.DptClass'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_sch', to='school.School'),
        ),
    ]
