# Generated by Django 3.0.1 on 2020-05-05 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SCRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caone', models.IntegerField()),
                ('catwo', models.IntegerField()),
                ('midterm', models.IntegerField()),
                ('cathree', models.IntegerField()),
                ('cafour', models.IntegerField()),
                ('project', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('total', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
    ]
