# Generated by Django 3.0.6 on 2020-05-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_institute'),
        ('student', '0002_auto_20200505_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
    ]
