# Generated by Django 3.0.6 on 2020-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0005_auto_20200508_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='sc_crse_reg', to='course.Course'),
        ),
    ]
