# Generated by Django 3.0.1 on 2020-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abb', models.CharField(default='None', max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
